name: Response Time CI

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  response-time:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: upptime/uptime-monitor@v1.36.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          command: response-time
